// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres.pmdlurfrwuvljkmnfwom:SupabasePass11%21%21@aws-1-us-east-1.pooler.supabase.com:5432/postgres",
  },
});
