"use client";

import * as React from "react";
import { useState } from "react";
import { X, FileText, Settings, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { SampleBrief } from "./SampleBrief";
import { FadeInOnMount } from "@/components/animations";
import Link from "next/link";

interface DemoModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type DemoMode = "select" | "sample" | null;

export function DemoModal({ isOpen, onClose }: DemoModalProps) {
  const [mode, setMode] = useState<DemoMode>(null);

  const handleClose = () => {
    setMode(null);
    onClose();
  };

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      handleClose();
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
          onClick={handleBackdropClick}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
            className="relative w-full max-w-4xl max-h-[90vh] overflow-hidden rounded-2xl border border-border bg-card shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              onClick={handleClose}
              className="absolute top-4 right-4 z-10 p-2 rounded-full bg-background/80 hover:bg-background transition-colors"
              aria-label="Close modal"
            >
              <X className="w-5 h-5 text-muted-foreground" />
            </button>

            {/* Content */}
            <div className="overflow-y-auto max-h-[90vh]">
              {!mode ? (
                <ModeSelection onSelectMode={setMode} onClose={handleClose} />
              ) : mode === "sample" ? (
                <SampleBriefView onBack={() => setMode(null)} />
              ) : null}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

function ModeSelection({
  onSelectMode,
  onClose,
}: {
  onSelectMode: (mode: DemoMode) => void;
  onClose: () => void;
}) {
  return (
    <FadeInOnMount>
      <div className="p-8 md:p-12">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-pink-500/10 border border-pink-500/20 mb-4">
            <Sparkles className="w-4 h-4 text-pink-500" />
            <span className="text-sm font-medium text-pink-500">
              Experience AI Employees
            </span>
          </div>
          <h2 className="text-3xl font-display font-bold mb-3">
            See AI Employees in Action
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Choose how you&apos;d like to explore our AI employee briefs. View a
            sample instantly or configure your own personalized demo.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6 max-w-2xl mx-auto">
          {/* View Sample Option */}
          <button
            onClick={() => onSelectMode("sample")}
            className="group relative p-6 rounded-xl border-2 border-border bg-card hover:border-pink-500/50 hover:bg-pink-500/5 transition-all text-left"
          >
            <div className="w-12 h-12 rounded-lg bg-pink-500/10 flex items-center justify-center mb-4 group-hover:bg-pink-500/20 transition-colors">
              <FileText className="w-6 h-6 text-pink-500" />
            </div>
            <h3 className="text-xl font-display font-semibold mb-2">
              View Sample Brief
            </h3>
            <p className="text-sm text-muted-foreground mb-4">
              See a real example of a weekly strategic intelligence brief
              generated by our AI Researcher.
            </p>
            <span className="text-sm font-medium text-pink-500 group-hover:underline">
              View sample →
            </span>
          </button>

          {/* Configure Your Own Option */}
          <Link href="/agents/demo" onClick={onClose}>
            <button className="group relative w-full p-6 rounded-xl border-2 border-border bg-card hover:border-pink-500/50 hover:bg-pink-500/5 transition-all text-left">
              <div className="w-12 h-12 rounded-lg bg-accent-purple/10 flex items-center justify-center mb-4 group-hover:bg-accent-purple/20 transition-colors">
                <Settings className="w-6 h-6 text-accent-purple" />
              </div>
              <h3 className="text-xl font-display font-semibold mb-2">
                Configure Your Own
              </h3>
              <p className="text-sm text-muted-foreground mb-4">
                Customize your demo with your competitors and focus areas for a
                personalized brief experience.
              </p>
              <span className="text-sm font-medium text-accent-purple group-hover:underline">
                Start configuring →
              </span>
            </button>
          </Link>
        </div>

        <p className="text-center text-sm text-muted-foreground mt-8">
          No signup required. Demo uses sample data.
        </p>
      </div>
    </FadeInOnMount>
  );
}

function SampleBriefView({ onBack }: { onBack: () => void }) {
  return (
    <div className="p-6 md:p-8">
      <div className="flex items-center gap-4 mb-6">
        <Button variant="outline" size="sm" onClick={onBack}>
          ← Back
        </Button>
        <div>
          <h2 className="text-xl font-display font-semibold">
            Sample Weekly Brief
          </h2>
          <p className="text-sm text-muted-foreground">
            Generated by AI Researcher
          </p>
        </div>
      </div>
      <SampleBrief />
    </div>
  );
}
